[package]
name = "dgaard-rest"
version = "0.1.0"
edition = "2024"

[lib]
name = "dgaard_rest"
path = "src/lib.rs"

[[bin]]
name = "dgaard-rest"
path = "src/main.rs"

[dependencies]
arc-swap.workspace = true
argh.workspace = true
axum.workspace = true
dgaard-engine.workspace = true
env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "net", "signal", "time"] }
toml.workspace = true

[dev-dependencies]
dgaard-engine.workspace = true
tempfile.workspace = true
tower.workspace = true
