[package]
name = "dgaard"
authors = ["Sébastien LUNDI"]
description = "A high-performance, stratified DNS security proxy for OpenWrt and SME networks. Featuring DGA detection, Shannon entropy analysis, multi-language N-Gram models, and zero-copy filtering. Built for speed and privacy."
readme = "README.md"
license = "Apache-2.0"
repository = "https://codeberg.org/slundi/dgaard"
keywords = ["dns", "proxy", "security", "filter", "heuristics"]
categories = ["network-programming", "embedded-software", "cryptography"]
version = "0.2.0"
edition = "2024"

[dependencies]
dgaard-engine.workspace = true
thiserror.workspace = true
getrandom.workspace = true
num_cpus.workspace = true
# Async runtime - 'rt' and 'macros' only to keep binary size small for OpenWrt
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "net", "io-util", "sync", "signal", "time"] }

# DNS Protocol handling and for Domain/TLD parsing logic
hickory-resolver.workspace = true
# to handle multiple socket on the same port
socket2.workspace = true

# Fast hashing for the u64 fingerprints (ID-ing domains/rules)
twox-hash.workspace = true

# Configuration parsing
toml-span.workspace = true

# High-performance matching
# RegexSet is used for the "Complex" rule tier
regex.workspace = true

# For lexical analysis
aho-corasick.workspace = true

url.workspace = true

# to have an HTTP client availble to download lists
hyper.workspace = true
hyper-rustls.workspace = true
rustls.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true

# Finite State Transducers for memory-efficient suffix/wildcard matching
fst.workspace = true

# Bloom Filter for NRD and large blocklists (Low RAM footprint)
bloom.workspace = true

# CLI argument parsing
gumdrop.workspace = true

# Logging (Lightweight)
log.workspace = true
env_logger.workspace = true

# Binary serialization: manual implementation for stats (no serde overhead)
rkyv.workspace = true

# Used for the 'Hot Cache' / Favorites
lru.workspace = true

dashmap.workspace = true
arc-swap.workspace = true
bitflags.workspace = true
