#!/bin/sh /etc/rc.common
# /etc/init.d/dgaard

USE_PROCD=1
START=94
STOP=05

PROG=/usr/bin/dgaard
CONFIG=/etc/dgaard/config.toml
PIDFILE=/var/run/dgaard.pid

start_service() {
    [ -f "$CONFIG" ] || return 1

    procd_open_instance
    procd_set_param command "$PROG" -c "$CONFIG"
    procd_set_param pidfile "$PIDFILE"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param limits core="0"
    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "dgaard"
}
