[package]
name = "dgaard-daemon"
version = "0.1.0"
edition = "2024"

[lib]
name = "dgaard_daemon"
path = "src/lib.rs"

[[bin]]
name = "dgaard-daemon"
path = "src/main.rs"

[dependencies]
arc-swap.workspace = true
argh.workspace = true
dgaard-engine.workspace = true
env_logger.workspace = true
getrandom.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "net", "io-util", "sync", "signal", "time"] }
toml-span.workspace = true

[dev-dependencies]
tempfile.workspace = true
twox-hash.workspace = true
