[package]
name = "dgaard-monitor-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "dgaard_monitor_core"
path = "src/lib.rs"

[dependencies]
bitflags.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-rustls.workspace = true
hyper-util.workspace = true
inotify.workspace = true
rusqlite.workspace = true
rustls = { workspace = true }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "net", "io-util", "io-std", "sync", "time", "fs"] }

[dev-dependencies]
tempfile.workspace = true
