// Schema for config.toml (the dgaard DNS proxy engine).
//
// Every key, type, accepted enum value and default below is transcribed from
// the Rust source — `dgaard-engine/src/config/parser.rs` for the key names and
// accepted values, `dgaard-engine/src/config/model.rs` for the defaults — and
// deliberately NOT from config.example.toml, which has drifted from both (see
// DESIGN.md §10).

export const ENGINE_SCHEMA = {
  id: 'engine',
  file: 'config.toml',
  title: 'dgaard engine',
  banner: ['Dgaard Configuration File'],
  sections: [
    {
      path: 'server',
      title: 'Server',
      doc: 'Listener address, client ACL and the order of the filter pipeline.',
      fields: [
        {
          key: 'listen_addr',
          type: 'socketaddr',
          default: '127.0.0.1:53',
          placeholder: '192.168.1.1:53',
          doc: 'Address and port the proxy listens on (53 in production, an\nunprivileged port for development).',
        },
        {
          key: 'mode',
          type: 'enum',
          values: ['forwarder', 'recursive'],
          default: 'forwarder',
          doc: 'Resolution backend for queries that survive the filter pipeline.\n"forwarder" delegates to the servers in [forwarder];\n"recursive" resolves iteratively from the root hints.',
        },
        {
          key: 'allowed_networks',
          type: 'cidr-list',
          default: ['127.0.0.1/32', '192.168.1.0/24'],
          doc: 'Networks allowed to use this proxy. Queries from addresses outside\nthis list are dropped.',
        },
        {
          key: 'stats_socket_path',
          type: 'path',
          default: '/tmp/dgaard_stats.sock',
          doc: 'Unix socket used to stream telemetry to the dashboard / TUI.\nMust match input.socket in dgaard-monitor.toml.',
        },
        {
          key: 'block_idn',
          type: 'bool',
          default: true,
          doc: 'Block every domain containing non-ASCII (Punycode / IDN) labels\nbefore any other filter runs. Must be false to use [security.idn].',
        },
        {
          key: 'metrics_listen',
          type: 'socketaddr',
          optional: true,
          default: null,
          placeholder: '127.0.0.1:9153',
          doc: 'Optional Prometheus scrape endpoint exposing /metrics in OpenMetrics\ntext format. 9153 is the conventional port for DNS exporters (CoreDNS).\nUse 0.0.0.0:9153 to allow scraping from a remote Prometheus on the LAN.\nCounters: dgaard_queries_total, _blocked, _allowed, _proxied.',
        },
        {
          key: 'pipeline',
          type: 'ordered-enum-list',
          values: ['Whitelist', 'HotCache', 'StaticBlock', 'SuffixMatch', 'Heuristics', 'Upstream'],
          default: [
            'Whitelist',
            'HotCache',
            'StaticBlock',
            'SuffixMatch',
            'Heuristics',
            'Upstream',
          ],
          doc: 'Ordered processing stages. The first stage producing a verdict\nshort-circuits the rest. The default order is tuned for OpenWrt:\ninstant pass, memory hits, exact match, wildcards, maths, network.',
        },
      ],
    },
    {
      path: 'server.runtime',
      title: 'Runtime',
      doc: 'Tokio runtime tuning. The defaults target embedded hardware.',
      fields: [
        {
          key: 'worker_threads',
          type: 'worker-threads',
          default: 'auto',
          doc: '"auto" uses one thread per logical CPU core (desktop/server).\nAn integer forces a specific count — pin to 1 on OpenWrt.',
        },
        {
          key: 'stack_size',
          type: 'int',
          rust: 'usize',
          default: 2097152,
          doc: 'Stack size per worker thread, in bytes. 8388608 (8 MiB) matches the\nusual desktop default; 2097152 (2 MiB) saves RAM on OpenWrt.',
        },
        {
          key: 'max_blocking_threads',
          type: 'int',
          rust: 'usize',
          default: 512,
          doc: 'Depth of the per-worker blocking task queue before requests are\nrejected with a backpressure error.',
        },
        {
          key: 'max_concurrent_queries',
          type: 'int',
          rust: 'usize',
          default: 1024,
          doc: 'Maximum DNS queries in flight simultaneously. Beyond this limit new\nqueries get an immediate SERVFAIL instead of spawning a task, which\nprevents OOM under a UDP flood. Use 128–256 on constrained devices.',
        },
      ],
    },
    {
      path: 'security.structure',
      title: 'Structure',
      doc: 'Cheapest filters in the pipeline: syntactic sanity checks on labels,\nrun first to drop malformed or tunneling traffic early.',
      fields: [
        {
          key: 'max_subdomain_depth',
          type: 'int',
          rust: 'u8',
          default: 5,
          doc: 'Maximum number of dot-separated labels. More than 5 often indicates\ntunneling (data.part1.bin.zone.attacker.com).',
        },
        {
          key: 'max_domain_length',
          type: 'int',
          rust: 'u16',
          default: 128,
          doc: 'Maximum FQDN length in bytes. RFC 1035 allows 253; tighten for\nembedded use.',
        },
        {
          key: 'force_lowercase_ascii',
          type: 'bool',
          default: true,
          doc: 'Reject domains containing anything outside [a-z0-9.\\-_].\nMust be false to use [security.idn].',
        },
        {
          key: 'block_chaos_class',
          type: 'bool',
          default: true,
          doc: 'Answer DNS CHAOS class (qclass=3) queries with REFUSED instead of\nforwarding them. `dig CH TXT version.bind` fingerprints the resolver —\na forwarding proxy should never answer these for its upstream.',
        },
        {
          key: 'max_txt_record_length',
          type: 'int',
          rust: 'u16',
          default: 128,
          doc: 'Maximum byte length of a single TXT value. SPF/DKIM records are\ntypically under 200 bytes; exfiltration tools use the 255-byte maximum.',
        },
        {
          key: 'max_answers_per_query',
          type: 'int',
          rust: 'u8',
          default: 10,
          doc: 'Block responses carrying more answer records than this.',
        },
      ],
    },
    {
      path: 'security.lexical',
      title: 'Lexical',
      doc: 'Keyword filtering for parental control. Blocks whole content categories\nwithout loading a blocklist of millions of records into RAM.',
      fields: [
        {
          key: 'enabled',
          type: 'bool',
          default: true,
          doc: 'Master switch for keyword filtering.',
        },
        {
          key: 'banned_keywords',
          type: 'string-list',
          default: [],
          doc: 'Keywords to block. Tailor them to the language(s) you want to filter.\nExample: casino, gambling, porn, sex.',
        },
        {
          key: 'strict_keyword_matching',
          type: 'bool',
          default: true,
          doc: 'true — the keyword must be a complete label or a hyphen-separated\nsegment (avoids the Scunthorpe problem). false — plain substring\nmatching: more aggressive, more false positives.',
        },
      ],
    },
    {
      path: 'security.intelligence',
      title: 'Intelligence (DGA)',
      doc: 'Lexical and statistical analysis of domain names — the "brain".\nDetects algorithmically generated domains that blocklists miss.',
      fields: [
        {
          key: 'enabled',
          type: 'bool',
          default: true,
          doc: 'Master switch for all heuristic checks.',
        },
        {
          key: 'entropy_threshold',
          type: 'float',
          default: 4.0,
          step: 0.1,
          doc: 'Shannon entropy threshold for the second-level domain. Typical range\n3.5 (strict) to 4.5 (lenient). Higher is more tolerant.',
        },
        {
          key: 'entropy_fast',
          type: 'bool',
          default: true,
          doc: 'Fast ASCII-only entropy (zero heap allocation, ideal for OpenWrt)\nrather than the HashMap-based full Unicode implementation.',
        },
        {
          key: 'min_word_length',
          type: 'int',
          rust: 'usize',
          default: 8,
          doc: 'Minimum SLD length before entropy and n-gram analysis apply.\nShort labels such as t.co are skipped to avoid false positives.',
        },
        {
          key: 'consonant_ratio_threshold',
          type: 'float',
          default: 0.6,
          step: 0.05,
          min: 0,
          max: 1,
          doc: 'Maximum consonant ratio before a label counts as unpronounceable.\n0.6 is very aggressive: codeberg is 5 consonants / 8 letters = 0.625.',
        },
        {
          key: 'max_consonant_sequence',
          type: 'int',
          rust: 'usize',
          default: 5,
          doc: 'Maximum consecutive consonants. Normal words rarely exceed 4\n("strength").',
        },
        {
          key: 'use_ngram_model',
          type: 'bool',
          default: false,
          doc: 'Score domains against language models. A domain must pass at least\nONE model to be allowed (OR logic).',
        },
        {
          key: 'ngram_use_embedded',
          type: 'bool',
          default: true,
          doc: 'true — embedded Markov matrices (~2.7 KB per language, zero-alloc,\nno external files; best for OpenWrt).\nfalse — load full n-gram tables from the .bin files below (2–5 MB per\nlanguage, higher accuracy, file I/O at startup).',
        },
        {
          key: 'ngram_embedded_languages',
          type: 'string-list',
          values: ['english', 'french', 'german', 'spanish', 'italian'],
          default: ['english', 'french'],
          doc: 'Languages for embedded mode. Add the language(s) your users speak to\navoid false positives.',
        },
        {
          key: 'ngram_models',
          type: 'source-list',
          default: ['/etc/dgaard/models/english.bin', '/etc/dgaard/models/french.bin'],
          doc: 'External model files, used only when ngram_use_embedded = false.',
        },
        {
          key: 'ngram_probability_threshold',
          type: 'float',
          default: -4.0,
          step: 0.5,
          doc: 'Log-probability threshold. Domains scoring below this in ALL models\nare blocked. Typical range -6.0 (strict) to -3.0 (lenient).',
        },
        {
          key: 'drop_entries_hard_blocked_at_load',
          type: 'bool',
          default: false,
          doc: 'Drop blacklist entries whose SLD already trips the entropy / consonant\nheuristics at LOAD time, to save memory. Whitelists are never dropped.\n\nWARNING: this can silently UN-BLOCK explicitly listed domains. Entropy\nis not a query-time block — it only adds points (at most 7) to the\nsuspicion score, below the default blocking_threshold of 10. A dropped\nblacklist entry is re-blocked only if other signals push it over the\nthreshold. If in doubt, leave this off.',
        },
      ],
    },
    {
      path: 'security.idn',
      title: 'IDN',
      doc: 'Internationalized domain name policy. Any mode other than "Off"\nrequires server.block_idn = false AND\nsecurity.structure.force_lowercase_ascii = false, otherwise every\nnon-ASCII label is dropped before this filter runs and dgaard refuses\nto start on the contradiction.',
      fields: [
        {
          key: 'mode',
          type: 'enum',
          values: ['Off', 'Strict', 'Smart'],
          default: 'Off',
          doc: 'Off — no IDN filtering (the coarse gates above handle it).\nStrict — block every non-ASCII label.\nSmart — allow the scripts listed below, block the rest.',
        },
        {
          key: 'allowed_scripts',
          type: 'string-list',
          default: ['Latin', 'WesternEuropean'],
          doc: 'Unicode scripts permitted in Smart mode.',
        },
      ],
    },
    {
      path: 'security.qtype_warden',
      title: 'QType warden',
      doc: 'Blocks queries by record type before any domain processing — the\ncheapest possible filter (a u16 lookup, no string comparison).',
      fields: [
        {
          key: 'enabled',
          type: 'bool',
          default: true,
          doc: 'Master switch for query-type policy enforcement.',
        },
        {
          key: 'blocked_types',
          type: 'int-list',
          default: [10, 13, 255],
          presets: { NULL: 10, HINFO: 13, ANY: 255, AXFR: 252, TXT: 16, SRV: 33 },
          doc: 'DNS record type numbers (RFC 1035 §3.2.2) to block.\nNULL (10) — tunneling (iodine, dnscat2).\nHINFO (13) — host info leakage.\nANY (255) — amplification attacks.\nAXFR (252) — zone transfer, never legitimate from a client.',
        },
      ],
    },
    {
      path: 'security.rebinding_shield',
      title: 'Rebinding shield',
      doc: 'Rejects upstream answers mapping a public domain to a private or\nreserved IP — the DNS rebinding attack vector. Covers RFC 1918, 1122,\n6598, 3927, 4291 and 4193 ranges in both address families.',
      fields: [
        {
          key: 'enabled',
          type: 'bool',
          default: true,
          doc: 'Master switch for the rebinding shield.',
        },
        {
          key: 'block_ptr_leak',
          type: 'bool',
          default: true,
          doc: 'Answer PTR queries (*.in-addr.arpa, *.ip6.arpa) for private, loopback\nand link-local ranges locally instead of forwarding them to a public\nresolver, which would expose internal host names and LAN topology.',
        },
      ],
    },
    {
      path: 'security.low_ttl',
      title: 'Low TTL',
      doc: 'Very short TTLs are characteristic of fast-flux malware. Legitimate\nCDNs use them too, so this adds suspicion points rather than blocking.',
      fields: [
        {
          key: 'enabled',
          type: 'bool',
          default: true,
          doc: 'Master switch for TTL-based scoring.',
        },
        {
          key: 'threshold_secs',
          type: 'int',
          rust: 'u32',
          default: 10,
          doc: 'Responses with min_ttl below this add LOW_TTL suspicion points.',
        },
        {
          key: 'min_ttl_floor_secs',
          type: 'int',
          rust: 'u32',
          optional: true,
          default: null,
          example: 30,
          doc: 'Optional cache TTL floor. Any TTL below this value is clamped upward\nbefore caching, preventing fast-flux domains from bypassing the cache\nwith near-zero TTLs. Unset leaves observed TTLs unchanged.',
        },
      ],
    },
    {
      path: 'security.asn_filter',
      title: 'ASN filter',
      doc: 'Blocks answers resolving into operator-supplied CIDR ranges — mining\npools, bulletproof hosting, known C2 networks. Catches fast-flux\ncampaigns that rotate domains but keep a stable hosting footprint.\nRanges are pre-parsed at startup; matching is O(1) per IP.',
      fields: [
        {
          key: 'enabled',
          type: 'bool',
          default: false,
          doc: 'Master switch. Requires explicit threat-intelligence input.',
        },
        {
          key: 'blocked_ranges',
          type: 'cidr-list',
          default: [],
          doc: 'IPv4 and IPv6 CIDR ranges to block, in one list.\nSource them from feeds such as the Spamhaus ASN DROP list or abuse.ch.',
        },
      ],
    },
    {
      path: 'security.scoring',
      title: 'Scoring',
      doc: 'Suspicion score thresholds. The two lower tiers only affect telemetry\nemitted on the stats socket, not blocking behaviour.',
      fields: [
        {
          key: 'blocking_threshold',
          type: 'int',
          rust: 'u8',
          default: 10,
          doc: 'Score at or above which a domain is blocked.',
        },
        {
          key: 'highly_suspicious_threshold',
          type: 'int',
          rust: 'u8',
          default: 7,
          doc: 'Score at or above which a domain is forwarded but always emitted as a\nHighlySuspicious event.',
        },
        {
          key: 'suspicious_threshold',
          type: 'int',
          rust: 'u8',
          default: 4,
          doc: 'Score at or above which a domain is emitted as a Suspicious event —\nonly when log_suspicious is true.',
        },
        {
          key: 'log_suspicious',
          type: 'bool',
          default: false,
          doc: 'Emit Suspicious events for domains between suspicious_threshold and\nhighly_suspicious_threshold.',
        },
      ],
    },
    {
      path: 'security.geo_ip',
      title: 'GeoIP',
      doc: 'Country-based suspicion scoring against a MaxMind-format database,\nopened with mmap to minimise RAM. Requires a build with the `geoip`\nfeature (cargo build --features geoip); enabling it on a default build\nis rejected at startup. Off by default because CDN edge IPs make\ncountry signals noisy.',
      fields: [
        { key: 'enabled', type: 'bool', default: false, doc: 'Master switch for GeoIP scoring.' },
        {
          key: 'database_path',
          type: 'path',
          default: '/etc/dgaard/GeoLite2-Country.mmdb',
          doc: 'Path to a MaxMind-format MMDB file (GeoLite2-Country, GeoIP2-Country,\nDB-IP or ip2location equivalents). Empty disables the check.',
        },
        {
          key: 'suspicious_countries',
          type: 'string-list',
          default: [],
          doc: 'ISO 3166-1 alpha-2 country codes considered suspicious, e.g. RU, CN.',
        },
        {
          key: 'suspicious_country_score',
          type: 'int',
          rust: 'u8',
          default: 3,
          doc: 'Suspicion points added per matching IP. 10 hard-blocks on its own.',
        },
      ],
    },
    {
      path: 'security.special_use',
      title: 'Special-use domains',
      doc: 'RFC 6761 isolation: never forward reserved or internal TLDs to a public\nresolver. Always enforced when enabled: .local, .localhost, .invalid,\n.test, .example.',
      fields: [
        {
          key: 'enabled',
          type: 'bool',
          default: true,
          doc: 'Master switch for special-use domain isolation.',
        },
        {
          key: 'extra_local_tlds',
          type: 'tld-list',
          default: [],
          doc: 'Additional TLDs to isolate, common in split-horizon deployments:\ncorp, lan, internal, home, intranet. Lowercase, no leading dot.',
        },
      ],
    },
    {
      path: 'security.dnssec',
      title: 'DNSSEC',
      doc: 'Validation through a side-channel hickory resolver running in parallel\nwith the forwarded query, so the added latency is only the difference\nbetween the two response times. Unsigned zones and unreachable\nvalidators fail open. Note: this doubles outgoing queries.',
      fields: [
        {
          key: 'enabled',
          type: 'bool',
          default: false,
          doc: 'Master switch for DNSSEC validation.',
        },
        {
          key: 'action',
          type: 'enum',
          values: ['block', 'log'],
          default: 'block',
          doc: 'What to do on a BOGUS result.\nblock — return SERVFAIL (the RFC-standard DNSSEC failure response).\nlog — forward the response unchanged and log the event; useful during\na trial period to measure the false-positive rate.',
        },
      ],
    },
    {
      path: 'security.custom_flags',
      title: 'Custom flags',
      repeatable: true,
      doc: 'User-defined threat-intelligence feeds, each bound to one bit of the\nupper half of StatBlockReason. A hit adds suspicious_score to the\nquery total and sets the bit in telemetry. At most 16 entries.',
      entry: {
        labelKey: 'code',
        labelFallback: 'flag',
        fields: [
          {
            key: 'bit',
            type: 'int',
            rust: 'u8',
            min: 16,
            max: 31,
            default: 16,
            example: 16,
            required: true,
            doc: 'Bit index in StatBlockReason. Must be 16–31 and unique.',
          },
          {
            key: 'code',
            type: 'string',
            default: '',
            example: 'AI_GENERATED',
            required: true,
            doc: 'Short machine-readable identifier used in JSON and log output,\ne.g. AI_GENERATED.',
          },
          {
            key: 'name',
            type: 'string',
            default: '',
            example: 'AI generated domains',
            doc: 'Human-readable label shown in the TUI and CLI.',
          },
          {
            key: 'description',
            type: 'string',
            default: '',
            example: 'Domains flagged by an LLM-assisted feed',
            doc: 'Freeform description; informational only, never sent on the wire.',
          },
          {
            key: 'suspicious_score',
            type: 'int',
            rust: 'u8',
            default: 1,
            example: 4,
            doc: 'Suspicion points added when this flag triggers.',
          },
          {
            key: 'list_path',
            type: 'source-list',
            default: [],
            example: ['/etc/dgaard/lists/ai_generated.txt'],
            doc: 'Plain-text domain lists (one domain per line, # comments stripped).',
          },
        ],
      },
    },
    {
      path: 'forwarder',
      title: 'Forwarder',
      doc: 'Resolvers used when server.mode = "forwarder".\nRenamed from [upstream]; the parser rejects the old name outright.',
      fields: [
        {
          key: 'servers',
          type: 'source-list',
          itemType: 'socketaddr',
          default: ['1.1.1.1:53', '9.9.9.9:53'],
          doc: 'Ordered resolver addresses in ip:port form.',
        },
        {
          key: 'timeout_ms',
          type: 'int',
          rust: 'u64',
          default: 2000,
          doc: 'Per-query timeout. Unanswered queries are retried on the next server.',
        },
        {
          key: 'use_0x20_randomization',
          type: 'bool',
          default: true,
          doc: 'DNS0x20 case randomization (Dagon et al., 2008). Randomly flips the\ncase of ASCII letters in the outgoing QNAME; a compliant upstream\nechoes it back verbatim, so mismatched responses are rejected as\nforged. Hardens against Kaminsky-style poisoning at zero cost.\nSet false if your upstreams normalize case — some non-compliant\nservers do, which would time out every query.',
        },
      ],
    },
    {
      path: 'recursive',
      title: 'Recursive resolver',
      doc: 'Iterative resolver tuning, used when server.mode = "recursive".',
      fields: [
        {
          key: 'root_hints_path',
          type: 'path',
          optional: true,
          default: null,
          example: '/etc/dgaard/root.hints',
          doc: 'Optional BIND-style root hints file. Unset uses the compiled-in IANA\nroot server set, which is diffed against named.root weekly.',
        },
        {
          key: 'max_delegation_depth',
          type: 'int',
          rust: 'u8',
          default: 8,
          doc: 'Hard ceiling on delegation hops; defence in depth on top of the\ncycle detector.',
        },
        {
          key: 'max_queries_per_resolution',
          type: 'int',
          rust: 'u32',
          default: 64,
          doc: 'Cap on total upstream queries per client resolution. CNAME chase and\nout-of-zone NS lookups are amortised against the same budget so an\namplifying chain cannot escape it.',
        },
        {
          key: 'max_cname_depth',
          type: 'int',
          rust: 'u8',
          default: 10,
          doc: 'Maximum CNAME chain length before returning SERVFAIL.',
        },
        {
          key: 'query_timeout_ms',
          type: 'int',
          rust: 'u64',
          default: 3000,
          doc: 'Per-nameserver UDP query timeout.',
        },
        {
          key: 'qname_minimization',
          type: 'bool',
          default: true,
          doc: 'RFC 9156 QNAME minimization. Accepted today; the loop still sends the\nfull QNAME until the Phase 2 follow-up lands.',
        },
        {
          key: 'strict_bailiwick',
          type: 'bool',
          default: true,
          doc: 'true — refuse out-of-bailiwick referrals up front (a referral that\nwidens the zone is a classic cache-poisoning vector).\nfalse — lenient, more tolerant of misconfigured zones.',
        },
        {
          key: 'ns_concurrency',
          type: 'enum',
          values: ['sequential', 'staggered', 'parallel'],
          default: 'sequential',
          doc: 'How queries fan out across a zone\'s nameservers. Only "sequential" is\nimplemented today; the others are accepted for forward compatibility.',
        },
        {
          key: 'max_concurrent_queries',
          type: 'int',
          rust: 'u8',
          default: 2,
          doc: 'Extra launches for staggered mode, total for parallel mode. Kept small\nto avoid antisocial behaviour towards root and TLD operators.',
        },
        {
          key: 'ns_stagger_ms',
          type: 'int',
          rust: 'u64',
          default: 200,
          doc: 'Gap between staggered launches.',
        },
        {
          key: 'edns0_enabled',
          type: 'bool',
          default: true,
          doc: 'Advertise an EDNS0 OPT record on outgoing queries (RFC 6891).',
        },
        {
          key: 'edns0_udp_payload_size',
          type: 'int',
          rust: 'u16',
          default: 1232,
          doc: 'Buffer size advertised in the OPT record. 1232 is the DNS Flag Day\n2020 fragmentation-safe value.',
        },
        {
          key: 'save_top_domains',
          type: 'int',
          rust: 'u32',
          default: 2048,
          doc: 'Top-N most popular domains persisted to disk.',
        },
        {
          key: 'save_path',
          type: 'path',
          default: '/var/dgaard/top-domains.bin',
          doc: 'Where popularity snapshots are written (rkyv binary with an 8-byte\nheader). Identical writes are skipped to spare flash on idle routers.\nEmpty disables persistence.',
        },
        {
          key: 'save_interval_secs',
          type: 'int',
          rust: 'u64',
          default: 600,
          doc: 'How often the popularity snapshot is written. 0 disables persistence.',
        },
        {
          key: 'decay_half_life_secs',
          type: 'int',
          rust: 'u64',
          default: 86400,
          doc: 'Half-life of the popularity score.',
        },
      ],
    },
    {
      path: 'prefetch',
      title: 'Prefetch',
      doc: 'When a cache hit is about to expire, a refresh is queued on a bounded\nchannel and a worker rewrites the cache entry before a client has to\nwait for a fresh upstream round-trip.',
      fields: [
        {
          key: 'enabled',
          type: 'bool',
          default: true,
          doc: 'Master switch. When false the worker is never spawned.',
        },
        {
          key: 'interval_ms',
          type: 'int',
          rust: 'u64',
          default: 200,
          doc: 'Minimum gap between two prefetch resolutions. Smooths the spike when\nmany cache entries near their TTL ceiling on the same tick.',
        },
        {
          key: 'queue_capacity',
          type: 'int',
          rust: 'usize',
          default: 256,
          doc: 'Bounded channel depth. Excess requests are dropped and counted in\nprefetch_dropped_total rather than blocking the query path.',
        },
        {
          key: 'ttl_remaining_trigger_secs',
          type: 'int',
          rust: 'u32',
          default: 30,
          doc: 'Fire the prefetch when remaining TTL falls below this. 0 disables it.',
        },
      ],
    },
    {
      path: 'tld',
      title: 'TLD filtering',
      doc: 'Every entry must be canonical — lowercase, no leading dot. A\nnon-canonical entry aborts startup.',
      fields: [
        {
          key: 'allow_only',
          type: 'tld-list',
          default: [],
          doc: 'If non-empty, ONLY these TLDs resolve. Leave empty to allow all and\nuse exclude for targeted blocks.',
        },
        {
          key: 'exclude',
          type: 'tld-list',
          default: [],
          doc: 'TLDs always blocked. A generic starting point for high-risk TLDs:\ntop, xyz, bid, country, stream, gdn.',
        },
        {
          key: 'suspicious_tlds',
          type: 'tld-list',
          default: [],
          doc: 'Conditional blocking: blocks only when the domain also contains a\nbanned keyword. Which ccTLDs you treat as suspicious is a regional\nchoice — adjust for the countries you do or do not expect traffic from.',
        },
      ],
    },
    {
      path: 'nxdomain_hunting',
      title: 'NXDOMAIN hunting',
      doc: 'Detects botnet C2 beacon scanning by counting NXDOMAIN responses per\nclient in a sliding window.',
      fields: [
        { key: 'enabled', type: 'bool', default: true, doc: 'Master switch for NXDOMAIN hunting.' },
        {
          key: 'threshold',
          type: 'int',
          rust: 'u32',
          default: 15,
          doc: 'NXDOMAIN responses in the window before a client is flagged.',
        },
        {
          key: 'window_seconds',
          type: 'int',
          rust: 'u32',
          default: 60,
          doc: 'Sliding window duration.',
        },
        {
          key: 'action',
          type: 'enum',
          values: ['log', 'block_client'],
          default: 'log',
          doc: "log — record the event only.\nblock_client — drop the client's traffic via firewall integration for\nthe remainder of the window.",
        },
      ],
    },
    {
      path: 'tunneling_detection',
      title: 'Tunneling detection',
      doc: 'Monitors the rate and structure of subdomains to detect covert channels\nthat encode data in DNS labels (aGVsbG8=.attacker.com).',
      fields: [
        {
          key: 'enabled',
          type: 'bool',
          default: true,
          doc: 'Master switch for tunneling detection.',
        },
        {
          key: 'max_subdomains_per_minute',
          type: 'int',
          rust: 'u32',
          default: 50,
          doc: 'Maximum unique subdomains under one SLD per client per minute.',
        },
        {
          key: 'max_label_length',
          type: 'int',
          rust: 'u8',
          default: 60,
          doc: 'Maximum byte length of a single label. Base64 and hex payloads produce\nlabels much longer than legitimate names.',
        },
      ],
    },
    {
      path: 'sources',
      title: 'Sources',
      doc: 'Domain list sources and refresh schedule. Entries may be local paths or\nhttp(s) URLs. Find lists at https://filterlists.com/',
      fields: [
        {
          key: 'nrd_list_path',
          type: 'path',
          default: '/tmp/nrd_daily.txt',
          doc: 'Newly Registered Domains list, refreshed daily via cron.',
        },
        {
          key: 'blacklists',
          type: 'source-list',
          default: ['/etc/dgaard/lists/adaway.txt', '/etc/dgaard/lists/malware_domains.txt'],
          doc: 'Blocklists, in hosts or bare-domain format. Add region- or\nlanguage-specific lists for your users.',
        },
        {
          key: 'whitelists',
          type: 'source-list',
          default: [
            '/etc/dgaard/lists/personal_whitelist.txt',
            '/etc/dgaard/lists/cdn_providers.txt',
          ],
          doc: 'Whitelists. Entries here override every other filter, heuristics\nincluded.',
        },
        {
          key: 'update_interval_hours',
          type: 'int',
          rust: 'u32',
          default: 24,
          doc: 'How often lists are re-fetched.',
        },
        {
          key: 'retry_delay_mins',
          type: 'int',
          rust: 'u32',
          default: 30,
          doc: 'How long to wait before retrying a failed download.',
        },
        {
          key: 'host_index_path',
          type: 'path',
          default: '/var/dgaard/host_mapping.bin',
          doc: 'Binary index mapping each xxh3_64 hash to its source domain, so tools\ncan resolve a hash without loading the full blocklist. Empty disables.\nMust match input.index in dgaard-monitor.toml.',
        },
        {
          key: 'browser_rules_path',
          type: 'path',
          default: '/var/dgaard/browser_rules.txt',
          doc: 'Collects the ABP cosmetic / element-hiding / scriptlet rules the DNS\nfilter cannot apply. Import this file into uBlock Origin for full\nad blocking. Empty disables.',
        },
        {
          key: 'reload_timeout_secs',
          type: 'int',
          rust: 'u32',
          default: 15,
          doc: 'Maximum seconds for a full list reload. On timeout the operation is\naborted and the previously loaded engine stays active. 0 disables the\ntimeout.',
        },
      ],
    },
    {
      path: 'abp',
      title: 'AdBlock Plus lists',
      doc: 'ABP lists mix cosmetic (CSS) and network rules; dgaard extracts only\nwhat a DNS filter can act on.',
      fields: [
        {
          key: 'extract_domain_only',
          type: 'bool',
          default: true,
          doc: 'Extract only plain domain-level rules, skipping CSS cosmetic rules.',
        },
        {
          key: 'update_interval',
          type: 'int',
          rust: 'u32',
          default: 24,
          doc: 'Refresh interval for ABP lists, in hours.',
        },
      ],
    },
    {
      path: 'cache',
      title: 'Response cache',
      doc: 'TTL-aware LRU cache keyed by (domain, qtype). Response bytes are stored\nverbatim and the transaction ID is patched per query. Only answers with\nat least one record are cached — never SERVFAIL or blocked responses.',
      fields: [
        { key: 'enabled', type: 'bool', default: true, doc: 'Master switch for response caching.' },
        {
          key: 'max_entries',
          type: 'int',
          rust: 'usize',
          default: 10000,
          doc: 'LRU capacity. 10 000 entries is roughly 5–50 MiB depending on\nresponse size.',
        },
        {
          key: 'ttl_override',
          type: 'int',
          rust: 'u32',
          default: 0,
          doc: 'Replace the upstream TTL for every cached entry. 0 uses the TTL\nreturned by the resolver (recommended).',
        },
      ],
    },
    {
      path: 'overrides',
      title: 'Overrides',
      repeatable: true,
      doc: 'Force a fixed IP for a domain, bypassing every filter. Useful for\nsplit-horizon DNS, trusted domains that keep tripping heuristics, and\nredirecting a domain to a local service. Events are emitted with action\n"Override". A query for the other address family returns NOERROR with\nan empty answer so the client falls back gracefully.',
      entry: {
        labelKey: 'domain',
        labelFallback: 'override',
        fields: [
          {
            key: 'domain',
            type: 'string',
            default: '',
            required: true,
            example: 'nas.home',
            placeholder: '*.internal.corp',
            doc: 'Exact match ("example.com") or wildcard prefix ("*.example.com",\nwhich matches sub.example.com but not example.com itself).',
          },
          {
            key: 'to',
            type: 'string',
            default: '',
            required: true,
            example: '192.168.1.50',
            placeholder: '192.168.1.50',
            doc: 'IPv4 or IPv6 address to return.',
          },
        ],
      },
    },
  ],
};
